version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: tabdeal_user
      POSTGRES_PASSWORD: tabdeal_pass
      POSTGRES_DB: tabdeal_db
    ports:
      - "5432:5432"
    volumes:
        - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tabdeal_user -d tabdeal_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  django:
    build: .
    container_name: tabdeal
    command: sh -c "./wait-for-postgres.sh postgres python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  celery:
    build: .
    container_name: celery_worker
    command: sh -c "./wait-for-postgres.sh postgres celery -A tabdeal worker --loglevel=info"
    volumes:
      - .:/app
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      django:
        condition: service_started
volumes:
  postgres_data: