# Generated by Django 5.2.4 on 2025-09-24 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topuprequest',
            name='idempotency_key',
            field=models.CharField(blank=True, editable=False, max_length=255, unique=True),
        ),
    ]
