# Generated by Django 5.2.4 on 2025-09-24 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_topuprequest_idempotency_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='last_charged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
