# Generated by Django 5.2.4 on 2025-09-26 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_phonenumber_last_charged_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
