# Generated by Django 5.2.4 on 2025-09-27 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_phonenumber_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='reference',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
